In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
# importing for ANN
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
from keras.layers import Dropout,Conv2D,MaxPooling2D,Flatten
#import kaggle

In [4]:
pwd

'/content'

In [6]:
df=pd.read_csv('Churn Modeling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
print(df.shape)
print(df.info())
print(df.describe())

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [7]:
# Cleaning the column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace(r"[^\w_]", "", regex=True)
    .str.replace(r"_+", "_", regex=True)
)
df.columns

Index(['rownumber', 'customerid', 'surname', 'creditscore', 'geography',
       'gender', 'age', 'tenure', 'balance', 'numofproducts', 'hascrcard',
       'isactivemember', 'estimatedsalary', 'exited'],
      dtype='object')

In [8]:
y=df['exited']
X=df.drop(['exited'],axis=1)

In [9]:
X.columns

Index(['rownumber', 'customerid', 'surname', 'creditscore', 'geography',
       'gender', 'age', 'tenure', 'balance', 'numofproducts', 'hascrcard',
       'isactivemember', 'estimatedsalary'],
      dtype='object')

In [10]:
num_col=df.select_dtypes(include=np.number).columns
cat_col=df.select_dtypes(exclude=np.number).columns

skewness=df[num_col].skew()
print(skewness)

rownumber          0.000000
customerid         0.001149
creditscore       -0.071607
age                1.011320
tenure             0.010991
balance           -0.141109
numofproducts      0.745568
hascrcard         -0.901812
isactivemember    -0.060437
estimatedsalary    0.002085
exited             1.471611
dtype: float64

In [ ]:
#distrtibution of target variable

for i in num_col:
    plt.figure(figsize=(6,4))
    sns.histplot(df[i], kde=True)
    plt.title(f"Histogram of {i}")
    plt.show()
    plt.close()

In [ ]:

#outliers check
for i in df.columns:
    plt.figure(figsize=(6,4))
    sns.boxplot(df[i])
    plt.title(f"Boxplot of {i}")
    plt.show()
    plt.close()

In [11]:
# Dropping irrelevent columns
X.drop(columns=['rownumber','customerid','surname'],inplace=True)

In [ ]:
X['geography'].value_counts()

geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [12]:
# Mapping cat cols
X['gender']=X['gender'].map({'Male':1,'Female':0})
X = pd.get_dummies(X, columns=['geography'], drop_first=True)

In [ ]:
X.head()

,creditscore,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,geography_Germany,geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,False,False
1,608,0,41,1,83807.86,1,0,1,112542.58,False,True
2,502,0,42,8,159660.80,3,1,0,113931.57,False,False
3,699,0,39,1,0.00,2,0,0,93826.63,False,False
4,850,0,43,2,125510.82,1,1,1,79084.10,False,True

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Step 1: Train and Temp split
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Step 2: Validation and Test split
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42
)

# Step 3: Feature Scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# model=Sequential()
# model.add(Dense(256,activation='relu',input_dim=11))
# Dropout(0.2)
# model.add(Dense(128,activation='relu'))
# Dropout(0.3)
# model.add(Dense(64,activation='relu'))
# Dropout(0.3)
# model.add(Dense(32,activation='relu'))
# Dropout(0.3)
# model.add(Dense(16,activation='relu'))
# Dropout(0.3)
# model.add(Dense(1,activation='sigmoid'))

In [27]:
from tensorflow.keras.regularizers import l2
model=Sequential()
model.add(Dense(64, activation='relu',input_dim=X_train_scaled.shape[1],kernel_regularizer=l2(0.001)))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu', kernel_regularizer=l2(0.001)))
model.add(Dropout(0.2))
model.add(Dense(16, activation='relu', kernel_regularizer=l2(0.001)))
model.add(Dropout(0.2))
model.add(Dense(8, activation='relu', kernel_regularizer=l2(0.001)))
model.add(Dense(1, activation='sigmoid'))

In [28]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [29]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_14 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_15 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_16 (Dropout)            │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,521 (13.75 KB)

 Trainable params: 3,521 (13.75 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
from tensorflow.keras.callbacks import EarlyStopping
callback = EarlyStopping(
    monitor="val_loss",
    min_delta=0.001,
    patience=10,
    verbose=1,
    mode="auto"
)

In [31]:
history = model.fit(
    X_train_scaled,
    y_train,
    validation_data=(X_val_scaled, y_val),
    epochs=210,
    batch_size=32,
    verbose=1,
    callbacks=[callback]
)

Epoch 1/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7923 - loss: 0.5700 - val_accuracy: 0.8107 - val_loss: 0.4912
Epoch 2/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7924 - loss: 0.5111 - val_accuracy: 0.8107 - val_loss: 0.4610
Epoch 3/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7984 - loss: 0.4875 - val_accuracy: 0.8393 - val_loss: 0.4364
Epoch 4/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8264 - loss: 0.4621 - val_accuracy: 0.8660 - val_loss: 0.4100
Epoch 5/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8379 - loss: 0.4417 - val_accuracy: 0.8727 - val_loss: 0.3853
Epoch 6/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8446 - loss: 0.4181 - val_accuracy: 0.8720 - val_loss: 0.3748
Epoch 7/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8436 - loss: 0.4183 - val_accuracy: 0.8707 - val_loss: 0.3759
Epoch 8/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8523 - loss: 0.4009 - val_accuracy: 0.8693 - val_loss: 0.3736
Epoch 9/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8514 - loss: 0.3980 - val_accuracy: 0.8680 - val_loss: 0.3650
Epoch 10/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8533 - loss: 0.3944 - val_accuracy: 0.8707 - val_loss: 0.3588
Epoch 11/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8507 - loss: 0.3909 - val_accuracy: 0.8687 - val_loss: 0.3634
Epoch 12/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8529 - loss: 0.3849 - val_accuracy: 0.8727 - val_loss: 0.3583
Epoch 13/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8569 - loss: 0.3828 - val_accuracy: 0.8753 - val_loss: 0.3532
Epoch 14/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8557 - loss: 0.3796 - val_accuracy: 0.8733 - val_loss: 0.3530
Epoch 15/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8570 - loss: 0.3807 - val_accuracy: 0.8740 - val_loss: 0.3563
Epoch 16/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8561 - loss: 0.3782 - val_accuracy: 0.8767 - val_loss: 0.3543
Epoch 17/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8606 - loss: 0.3750 - val_accuracy: 0.8753 - val_loss: 0.3511
Epoch 18/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8569 - loss: 0.3733 - val_accuracy: 0.8740 - val_loss: 0.3493
Epoch 19/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8596 - loss: 0.3712 - val_accuracy: 0.8727 - val_loss: 0.3470
Epoch 20/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8550 - loss: 0.3702 - val_accuracy: 0.8747 - val_loss: 0.3495
Epoch 21/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8567 - loss: 0.3690 - val_accuracy: 0.8700 - val_loss: 0.3481
Epoch 22/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8603 - loss: 0.3690 - val_accuracy: 0.8720 - val_loss: 0.3429
Epoch 23/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8563 - loss: 0.3709 - val_accuracy: 0.8733 - val_loss: 0.3457
Epoch 24/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8586 - loss: 0.3687 - val_accuracy: 0.8747 - val_loss: 0.3474
Epoch 25/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8626 - loss: 0.3645 - val_accuracy: 0.8720 - val_loss: 0.3448
Epoch 26/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8617 - loss: 0.3635 - val_accuracy: 0.8700 - val_loss: 0.3472
Epoch 27/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8584 - loss: 0.3658 - val_accuracy: 0.8747 - val_loss: 0.3435
Epoch 28/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8584 - loss: 0.3658 - val_accuracy: 0.8660 - val_loss: 0.3539
Epoch 29/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8594 - loss: 0.3653 - val_accuracy: 0.8693 - val_loss: 0.3502
Epoch 30/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8611 - loss: 0.3636 - val_accuracy: 0.8673 - val_loss: 0.3522
Epoch 31/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8554 - loss: 0.3674 - val_accuracy: 0.8680 - val_loss: 0.3478
Epoch 32/210
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8581 - loss: 0.3639 - val_accuracy: 0.8667 - val_loss: 0.3555
Epoch 32: early stopping

In [32]:
test_loss, test_accuracy = model.evaluate(X_test_scaled, y_test)

print("Test Accuracy:", test_accuracy)

47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8627 - loss: 0.3657
Test Accuracy: 0.862666666507721

In [33]:
y_pred=model.predict(X_test_scaled)

47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [34]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.34766530990600586

In [35]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = model.predict(X_test_scaled)
y_pred = (y_pred > 0.4).astype(int)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[1098  102]
 [ 132  168]]
              precision    recall  f1-score   support

           0       0.89      0.92      0.90      1200
           1       0.62      0.56      0.59       300

    accuracy                           0.84      1500
   macro avg       0.76      0.74      0.75      1500
weighted avg       0.84      0.84      0.84      1500

In [ ]:
df['exited'].value_counts()

exited
0    7963
1    2037
Name: count, dtype: int64

In [142]:
class_weight = {0:1, 1:4}

history = model.fit(
    X_train_scaled,
    y_train,
    validation_data=(X_val_scaled, y_val),
    epochs=20,
    batch_size=32,
    class_weight=class_weight
)

Epoch 1/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.8637 - loss: 0.6444 - val_accuracy: 0.7780 - val_loss: 0.4752
Epoch 2/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8620 - loss: 0.6216 - val_accuracy: 0.7500 - val_loss: 0.5272
Epoch 3/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8789 - loss: 0.5800 - val_accuracy: 0.7780 - val_loss: 0.4972
Epoch 4/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8800 - loss: 0.5548 - val_accuracy: 0.7807 - val_loss: 0.4857
Epoch 5/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8861 - loss: 0.5169 - val_accuracy: 0.7880 - val_loss: 0.4922
Epoch 6/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8924 - loss: 0.4884 - val_accuracy: 0.7680 - val_loss: 0.5154
Epoch 7/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8969 - loss: 0.4791 - val_accuracy: 0.7873 - val_loss: 0.5045
Epoch 8/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9027 - loss: 0.4566 - val_accuracy: 0.7860 - val_loss: 0.5258
Epoch 9/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8986 - loss: 0.4543 - val_accuracy: 0.8020 - val_loss: 0.4891
Epoch 10/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9034 - loss: 0.4346 - val_accuracy: 0.7620 - val_loss: 0.5580
Epoch 11/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8986 - loss: 0.4318 - val_accuracy: 0.7820 - val_loss: 0.5269
Epoch 12/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9106 - loss: 0.3958 - val_accuracy: 0.7820 - val_loss: 0.5446
Epoch 13/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9097 - loss: 0.3946 - val_accuracy: 0.7887 - val_loss: 0.5419
Epoch 14/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9136 - loss: 0.3791 - val_accuracy: 0.7760 - val_loss: 0.5581
Epoch 15/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9139 - loss: 0.3756 - val_accuracy: 0.7860 - val_loss: 0.5677
Epoch 16/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9156 - loss: 0.3609 - val_accuracy: 0.7927 - val_loss: 0.5531
Epoch 17/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9224 - loss: 0.3458 - val_accuracy: 0.7733 - val_loss: 0.5860
Epoch 18/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9183 - loss: 0.3495 - val_accuracy: 0.7813 - val_loss: 0.6120
Epoch 19/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9190 - loss: 0.3569 - val_accuracy: 0.7747 - val_loss: 0.5908
Epoch 20/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9227 - loss: 0.3402 - val_accuracy: 0.7700 - val_loss: 0.6149

In [37]:
model.save("churn_pred_model.keras")

In [36]:
## Hyper parameter tuning using keras tuner

!pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 1.3 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [38]:
import keras_tuner as kt
from tensorflow.keras.optimizers import Adam
def build_model(hp):
    model = Sequential()

    # First hidden layer
    model.add(Dense(
        units=hp.Int('units_1', min_value=16, max_value=64, step=16),
        activation='relu',
        kernel_regularizer=l2(hp.Float('l2_1', 1e-4, 1e-2, sampling='log')),
        input_dim=X_train_scaled.shape[1]
    ))

    model.add(Dropout(
        hp.Float('dropout_1', min_value=0.1, max_value=0.4, step=0.1)
    ))

    # Second hidden layer
    model.add(Dense(
        units=hp.Int('units_2', min_value=8, max_value=32, step=8),
        activation='relu',
        kernel_regularizer=l2(hp.Float('l2_2', 1e-4, 1e-2, sampling='log'))
    ))

    model.add(Dropout(
        hp.Float('dropout_2', min_value=0.1, max_value=0.4, step=0.1)
    ))

    # Output layer
    model.add(Dense(1, activation='sigmoid'))

    # Learning rate tuning
    lr = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])

    model.compile(
        optimizer=Adam(learning_rate=lr),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [39]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=10,
    executions_per_trial=1,
    directory='keras_tuner_dir',
    project_name='customer_churn_tuning'
)

In [40]:
tuner.search(
    X_train_scaled,
    y_train,
    validation_data=(X_val_scaled, y_val),
    epochs=20,
    batch_size=32
)

Trial 10 Complete [00h 00m 19s]
val_accuracy: 0.871999979019165

Best val_accuracy So Far: 0.8733333349227905
Total elapsed time: 00h 03m 50s

In [41]:
best_hp = tuner.get_best_hyperparameters(num_trials=1)[0]

print("Best units_1:", best_hp.get('units_1'))
print("Best dropout_1:", best_hp.get('dropout_1'))
print("Best units_2:", best_hp.get('units_2'))
print("Best dropout_2:", best_hp.get('dropout_2'))
print("Best learning rate:", best_hp.get('learning_rate'))

Best units_1: 16
Best dropout_1: 0.1
Best units_2: 32
Best dropout_2: 0.30000000000000004
Best learning rate: 0.001

In [42]:
best_model = tuner.hypermodel.build(best_hp)

In [43]:
history = best_model.fit(
    X_train_scaled,
    y_train,
    validation_data=(X_val_scaled, y_val),
    epochs=20,
    batch_size=32
)

Epoch 1/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7666 - loss: 0.5808 - val_accuracy: 0.8133 - val_loss: 0.4885
Epoch 2/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8069 - loss: 0.5016 - val_accuracy: 0.8260 - val_loss: 0.4518
Epoch 3/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8081 - loss: 0.4768 - val_accuracy: 0.8320 - val_loss: 0.4337
Epoch 4/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8186 - loss: 0.4579 - val_accuracy: 0.8420 - val_loss: 0.4132
Epoch 5/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8260 - loss: 0.4339 - val_accuracy: 0.8640 - val_loss: 0.3924
Epoch 6/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8389 - loss: 0.4201 - val_accuracy: 0.8727 - val_loss: 0.3721
Epoch 7/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8393 - loss: 0.4048 - val_accuracy: 0.8680 - val_loss: 0.3653
Epoch 8/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8450 - loss: 0.3970 - val_accuracy: 0.8693 - val_loss: 0.3596
Epoch 9/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8454 - loss: 0.3887 - val_accuracy: 0.8707 - val_loss: 0.3536
Epoch 10/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8480 - loss: 0.3858 - val_accuracy: 0.8713 - val_loss: 0.3518
Epoch 11/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8476 - loss: 0.3841 - val_accuracy: 0.8720 - val_loss: 0.3495
Epoch 12/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8514 - loss: 0.3812 - val_accuracy: 0.8713 - val_loss: 0.3490
Epoch 13/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8510 - loss: 0.3770 - val_accuracy: 0.8733 - val_loss: 0.3466
Epoch 14/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8487 - loss: 0.3790 - val_accuracy: 0.8713 - val_loss: 0.3493
Epoch 15/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8513 - loss: 0.3767 - val_accuracy: 0.8747 - val_loss: 0.3464
Epoch 16/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8503 - loss: 0.3766 - val_accuracy: 0.8747 - val_loss: 0.3458
Epoch 17/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8500 - loss: 0.3713 - val_accuracy: 0.8773 - val_loss: 0.3423
Epoch 18/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8499 - loss: 0.3706 - val_accuracy: 0.8760 - val_loss: 0.3400
Epoch 19/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8507 - loss: 0.3726 - val_accuracy: 0.8740 - val_loss: 0.3396
Epoch 20/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8517 - loss: 0.3694 - val_accuracy: 0.8733 - val_loss: 0.3411

In [44]:
loss, accuracy = best_model.evaluate(X_test_scaled, y_test)
print("Test Accuracy:", accuracy)

47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8660 - loss: 0.3534
Test Accuracy: 0.8659999966621399

In [45]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = (best_model.predict(X_test_scaled) > 0.5).astype(int)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
[[1156   44]
 [ 157  143]]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1200
           1       0.76      0.48      0.59       300

    accuracy                           0.87      1500
   macro avg       0.82      0.72      0.75      1500
weighted avg       0.86      0.87      0.85      1500

In [46]:
# =========================
# CUSTOMER INPUTS
# =========================

creditscore = float(input("Enter Credit Score: "))
gender = input("Enter Gender (Male/Female): ")
age = float(input("Enter Age: "))
tenure = float(input("Enter Tenure: "))
balance = float(input("Enter Balance: "))
numofproducts = float(input("Enter Number of Products: "))
hascrcard = int(input("Has Credit Card? (1/0): "))
isactivemember = int(input("Is Active Member? (1/0): "))
estimatedsalary = float(input("Enter Estimated Salary: "))
geography = input("Enter Geography (France/Germany/Spain): ")

Enter Credit Score: 850
Enter Gender (Male/Female): F
Enter Age: 41
Enter Tenure: 6
Enter Balance: 160000
Enter Number of Products: 3
Has Credit Card? (1/0): 1
Is Active Member? (1/0): 1
Enter Estimated Salary: 120000
Enter Geography (France/Germany/Spain): France

In [47]:
# =========================
# ENCODING INPUTS
# =========================

# Gender encoding
if gender == 'Male':
    gender = 1
else:
    gender = 0

# Geography encoding
if geography == 'Germany':
    geography_Germany = 1
    geography_Spain = 0
elif geography == 'Spain':
    geography_Germany = 0
    geography_Spain = 1
else:   # France
    geography_Germany = 0
    geography_Spain = 0

# =========================
# CREATE INPUT ARRAY
# SAME ORDER AS TRAINING
# =========================

user_data = np.array([[
    creditscore,
    gender,
    age,
    tenure,
    balance,
    numofproducts,
    hascrcard,
    isactivemember,
    estimatedsalary,
    geography_Germany,
    geography_Spain
]])

# =========================
# SCALE INPUT
# =========================

user_data_scaled = scaler.transform(user_data)

# =========================
# PREDICT
# =========================

prediction = model.predict(user_data_scaled)

churn_probability = prediction[0][0]

print("\nChurn Probability:", churn_probability)

# =========================
# FINAL DECISION
# =========================

if churn_probability > 0.5:
    print("Prediction: Customer is likely to CHURN")
else:
    print("Prediction: Customer is NOT likely to churn")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

Churn Probability: 0.9297905
Prediction: Customer is likely to CHURN